customhost = "learninonemindb.cfkmmk2wmab8.ap-south-1.rds.amazonaws.com"
customuser = "Learn_in_one_min"
custompass = "Pranav01"
customdb = "Learn_in"
#custombucket = "addemployee"
customregion = "ap-south-1"
